import './js/Character';
import './js/bowman';
import './js/daemon';
import './js/magician';
import './js/swordsman';
import './js/undead';
import './js/zombie';
import './css/style.css';
import './js/app';